import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import '@/app/globals.css'

const inter = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Learn Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='fr'>
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}
